### ISSUE TITLE
專案環境建置

### ISSUE THREAD

**Issue by dopamine908** [dopamine908/math-sharing#3]
## 環境建置

先執行指令
```
sh project_install.sh
```
這個指令會安裝 docker 環境
並做 ``` composer install ``` 跟 ``` php artisan key:generate ```

```
vim /etc/hosts

// 加入這行
127.0.0.1 dev.math-sharing.com
```
開發用網址 : [https://dev.math-sharing.com:58443/](https://dev.math-sharing.com:58443/)

## 資料庫設定

從本地的 GUI 連入資料庫
```
Host : 127.0.0.1
Port : 53306
```

新增資料庫
```
math_sharing
```

## Redis

從本地的 GUI 連入資料庫
```
Host : 127.0.0.1
Port : 56379
```

**Comment by YNCBearz** [comment]
目前照文件測試ok!

-- 

[補充]

1. https://dev.math-sharing.com:58443/ 會出現以下畫面
<img width="1073" alt="螢幕快照 2021-08-14 19 44 29" src="https://user-images.githubusercontent.com/42233971/129455234-440dbfcf-dae4-4dc5-af9b-7f93cd003065.png">

我在其他專案是用直接輸入 【thisisunsafe】跳過，或者給docker一個憑證（有點忘記具體動作）
想問一下你們是怎麼用？

2. 根據這份文件，我有修改.env.example mysql的部分
目前push在branch: chore/laradock-environment，再問看git規範是應該推在哪？（or pull request)
